# Generated by Django 3.0.3 on 2020-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=32)),
                ('epass', models.CharField(max_length=32)),
                ('eemail', models.CharField(max_length=32)),
                ('eage', models.IntegerField()),
            ],
        ),
    ]
